version: "3"

x-logging: &default_logging
  logging:
    driver: "json-file"
    options:
      tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

volumes:
  loki: {}
  grafana: {}

services:
  loki:
    <<: *default_logging
    container_name: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - ${PWD}/loki/config.yaml:/etc/loki/loki-config.yaml
      - loki:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    <<: *default_logging
    container_name: grafana
    image: grafana/grafana:8.5.5
    restart: unless-stopped
    user: "104"
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true

  promtail:
    <<: *default_logging
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/promtail/config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml